name: Deploy Portfolio to GitHub Pages

on:
  # Exécute sur les pushs vers la branche principale
  push:
    branches: ["main"]

  # Permettre l'exécution manuelle depuis l'interface GitHub Actions
  workflow_dispatch:

# Définit les permissions du GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# N'autoriser qu'un seul déploiement à la fois
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci

      - name: Build with Vite
        run: |
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
